package model;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Sep 21 02:36:14 EEST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HighlyPaidEmployeesImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public HighlyPaidEmployeesImpl() {
    }
}

